[package]
name = "break-enforcer-s"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.2", features = ["derive"] }
color-eyre = "0.6.2"
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.58"
toml = "0.8.11"
